esphome:
  name: aircon
  platform: ESP8266
  board: esp12e

wifi:
  ssid: Progrium
  password: !secret wifi_password_jeff

api:
  password: !secret wifi_password_jeff

ota:
  password: !secret wifi_password_jeff

web_server:
  port: 80

logger:
  baud_rate: 0

# UART settings for Midea dongle (required)
uart:
  tx_pin: 1
  rx_pin: 3
  baud_rate: 9600

# Optional (if you want modify settings)
midea_dongle:
  strength_icon: true

# Main settings
climate:
  - platform: midea_ac
    name: "MRCOOL Garage"
    visual:
      min_temperature: 18 °C
      max_temperature: 25 °C
      temperature_step: 0.1 °C
    beeper: true
    custom_fan_modes:
      - SILENT
      - TURBO
    preset_eco: true
    preset_sleep: true
    preset_boost: true
    custom_presets:
      - FREEZE_PROTECTION
    swing_horizontal: true
    swing_both: true
    outdoor_temperature:
      name: "Temp"
    power_usage:
      name: "Power"
    humidity_setpoint:
      name: "Hum"
