esphome:
  name: clavemlux
  platform: ESP32
  board: featheresp32

wifi:
  ssid: "NotProgrium"
  password: !secret wifi_password

# web_server:
#   port: 80

logger:
  level: DEBUG

api:
  password: !secret wifi_password

ota:
  password: !secret wifi_password

output:
  - platform: ledc
    id: light_cold
    min_power: 0.00
    max_power: 1.00
    pin: A0
  - platform: ledc
    id: light_warm
    min_power: 0.00
    max_power: 1.00
    pin: A1

light:
  - platform: cwww
    name: Clavemlux Light
    cold_white: light_cold
    warm_white: light_warm
    cold_white_color_temperature: 6500 K
    warm_white_color_temperature: 2700 K
