wifi:
  ssid: NotProgrium
  password: !secret wifi_password

esphome:
  name: glidertron
  comment: Lockitron clone

web_server:
  port: 80

esp32:
  board: featheresp32

ota:
  password: !secret wifi_password

output:
  - platform: ledc
    id: motor_in1
    pin: A6
  - platform: ledc
    id: motor_in2
    pin: A7

fan:
  - platform: hbridge
    id: motor
    name: Lock Motor
    pin_a: motor_in1
    pin_b: motor_in2

logger:
  level: INFO
