substitutions:
  esphome_name: halloween-penta

esphome:
  name: ${esphome_name}
  platformio_options:
    board_build.flash_mode: dio

esp32:
  board: esp32-c3-devkitm-1
  framework:
    type: esp-idf

wifi:
  ssid: NotProgrium
  password: !secret wifi_password

logger:
  level: NONE
  baud_rate: 0

api:
  reboot_timeout: 60min
  password: !secret wifi_password

ota:
  - platform: esphome
    password: !secret wifi_password

time:
  - platform: homeassistant
    id: homeassistant_time

web_server:
  port: 80

i2c:
  sda: GPIO6
  scl: GPIO7
  scan: true
  id: I2C

sensor:
  - platform: uptime
    name: "Uptime Sensor"

  - platform: wifi_signal
    name: "WiFi Signal"
    update_interval: 60s

  - platform: internal_temperature
    name: "Internal Temperature"
    accuracy_decimals: 2
    update_interval: 30s

switch:
  - platform: restart
    name: Restart
    id: restart_switch

binary_sensor:
  - platform: gpio
    pin: 2
    name: Button_1
    filters:
      - invert:

  - platform: gpio
    pin: 8
    name: Button_2
    filters:
      - invert:

  - platform: gpio
    pin: 9
    name: Button_3
    filters:
      - invert:

output:
  - platform: ledc
    pin: GPIO5
    frequency: 19531Hz
    id: led_channel_1

  - platform: ledc
    pin: GPIO4
    frequency: 19531Hz
    id: led_channel_2

  - platform: ledc
    pin: GPIO1
    frequency: 19531Hz
    id: led_channel_3

  - platform: ledc
    pin: GPIO0
    frequency: 19531Hz
    id: led_channel_4

  - platform: ledc
    pin: GPIO3
    frequency: 19531Hz
    id: led_channel_5


light:
  - platform: monochromatic
    name: "LED-1"
    default_transition_length: 3s
    id: led1
    output: led_channel_1

  - platform: monochromatic
    name: "LED-2"
    default_transition_length: 3s
    id: led2
    output: led_channel_2

  - platform: monochromatic
    name: "LED-3"
    default_transition_length: 3s
    id: led3
    output: led_channel_3

  - platform: monochromatic
    name: "LED-4"
    default_transition_length: 3s
    id: led4
    output: led_channel_4

  - platform: monochromatic
    name: "LED-5"
    default_transition_length: 3s
    id: led5
    output: led_channel_5
