substitutions:
  esphome_name: halloween-penta
  friendly_name: Halloween Penta

esphome:
  name: ${esphome_name}
  friendly_name: ${friendly_name}
  platformio_options:
    board_build.flash_mode: dio

esp32:
  board: esp32-c3-devkitm-1
  framework:
    type: arduino

wifi:
  ssid: NotProgrium
  password: !secret wifi_password

logger:
  level: NONE
  baud_rate: 0

api:
  reboot_timeout: 60min
  encryption:
    key: !secret api_key_halloween

ota:
  - platform: esphome
    password: !secret wifi_password

time:
  - platform: homeassistant
    id: homeassistant_time

web_server:
  port: 80

i2c:
  sda: GPIO6
  scl: GPIO7
  scan: true
  id: I2C

sensor:
  - platform: uptime
    name: "Uptime Sensor"

  - platform: wifi_signal
    name: "WiFi Signal"
    update_interval: 60s

  - platform: internal_temperature
    name: "Internal Temperature"
    accuracy_decimals: 2
    update_interval: 30s

switch:
  - platform: restart
    name: Restart
    id: restart_switch

binary_sensor:
  - platform: gpio
    pin: 2
    name: Button 1
    internal: true
    filters:
      - invert:

  - platform: gpio
    pin: 8
    name: Button 2
    internal: true
    filters:
      - invert:

  - platform: gpio
    pin: 9
    name: Button 3
    internal: true
    filters:
      - invert:

output:
  - platform: ledc
    pin: GPIO5
    frequency: 19531Hz
    id: led_channel_1

  - platform: ledc
    pin: GPIO4
    frequency: 19531Hz
    id: led_channel_2

  - platform: ledc
    pin: GPIO1
    frequency: 19531Hz
    id: led_channel_3

  - platform: ledc
    pin: GPIO0
    frequency: 19531Hz
    id: led_channel_4

  - platform: ledc
    pin: GPIO3
    frequency: 19531Hz
    id: led_channel_5


light:
  - platform: monochromatic
    name: Strip 1
    id: strip_1
    default_transition_length: 3s
    output: led_channel_1
    internal: true

  - platform: monochromatic
    name: Strip 2
    id: strip_2
    default_transition_length: 3s
    output: led_channel_2
    internal: true

  - platform: partition
    name: UV Strip
    segments:
      - single_light_id: strip_1
      - single_light_id: strip_2
