esphome:
  name: quinledquad
  platform: ESP32
  board: esp32dev

wifi:
  ssid: NotProgrium
  password: !secret wifi_password

api:
  password: !secret wifi_password

ota:
  password: !secret wifi_password

logger:
  level: INFO

web_server:
  port: 80

output:
  - platform: ledc
    pin: 16
    frequency: 20000Hz
    id: LED_gpio_16
  - platform: ledc
    pin: 17
    frequency: 20000Hz
    id: LED_gpio_17
  - platform: ledc
    pin: 5
    frequency: 20000Hz
    id: LED_gpio_5
  - platform: ledc
    pin: 19
    frequency: 20000Hz
    id: LED_gpio_19

light:
  - platform: cwww
    name: "Garage Strips"
    cold_white: LED_gpio_16
    warm_white: LED_gpio_17
    cold_white_color_temperature: 153 mireds
    warm_white_color_temperature: 500 mireds
    constant_brightness: True
    default_transition_length: 2s
