esphome:
  name: uv
  platform: ESP32
  board: esp32dev

wifi:
  ssid: NotProgrium
  password: !secret wifi_password

api:
  password: !secret wifi_password

ota:
  - platform: esphome
    password: !secret wifi_password

logger:
  level: INFO

web_server:
  port: 80

output:
  - platform: ledc
    pin: 16
    frequency: 20000Hz
    id: LED_gpio_16
  - platform: ledc
    pin: 17
    frequency: 20000Hz
    id: LED_gpio_17
  - platform: ledc
    pin: 5
    frequency: 20000Hz
    id: LED_gpio_5
  - platform: ledc
    pin: 19
    frequency: 20000Hz
    id: LED_gpio_19

light:
  - platform: monochromatic
    name: "UV"
    output: LED_gpio_16
    default_transition_length: 2s
